version: '3.9'
name: 'nest-microservices'
services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres
    env_file:
      - .env
  rabbitmq:
    image: rabbitmq:3.9.28-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    env_file:
      - .env
volumes:
  postgres:
  rabbitmq:
